# -*- coding: utf-8 -*-
"""
Conținut nou pentru capitolele tehnice (IV.x și V.x) ale Raportului CS4.
FIDEL CODULUI REAL (easy-gait), cu cifre verificate (fișier:linie) și nuanțe oneste v2.

Structura: dict {ancora_heading: [paragrafe]}. Fiecare intrare e o listă de tupluri
(tip, text), unde tip ∈ {"p" body text, "h4" sub-heading bold}.

Conținutul înlocuiește paragrafele de CONȚINUT dintre heading-ul-ancoră și
următorul heading, PĂSTRÂND paragrafele cu imagini/tabele (gestionate de script).
"""

# Fiecare cheie = textul exact al heading-ului-ancoră din document (după care urmează conținutul nou).
SECTIONS = {

# ─────────────────────────── 4.2 DATASET SAMALA ─────────────────────────────
"Dataset principal: purtători de proteză transtibială – Samala et al. (2024)": [
("p", "Datasetul principal (Samala et al., 2024) conține înregistrări de la 30 de participanți purtători de proteză transtibială unilaterală (25 bărbați, 5 femei), cu o vârstă medie de ~53 de ani. Toate cele 30 de proteze sunt PASIVE: predominant de tip SACH (24 din 30), restul fiind picioare dinamice cu revenire de energie (ESR), sPace (Endolite) și mono-axiale — nicio gleznă acționată. Achiziția s-a realizat la mers cu viteză confortabilă pe un traseu drept, utilizând un sistem inerțial Noraxon eșantionat la 200 Hz, montat pe segmentele membrelor inferioare, simultan cu un sistem optic de captură a mișcării (OMC), de asemenea la 200 Hz, care oferă datele de referință (ground truth) pentru validarea cinematică."),
("p", "Sistemul Noraxon furnizează, pentru fiecare segment, orientarea (pitch) și accelerațiile pe trei axe. Spre deosebire de datasetul complementar Wassall, sistemul nu pune la dispoziție viteza unghiulară măsurată direct printr-un giroscop; din acest motiv, viteza unghiulară a tibiei — necesară algoritmilor de detecție — este obținută prin diferențiere numerică (gradient centrat) a unghiului de pitch, urmată de filtrare Butterworth la 15 Hz. Datele inerțiale (în format CSV, ~140 de parametri la 200 Hz) constituie intrarea principală pentru detecția evenimentelor de mers, delimitarea fazelor de sprijin și de balans și extragerea parametrilor temporali. Datele optice (pozițiile 3D ale markerilor, fișiere C3D) servesc exclusiv ca referință pentru validare. Cele două fluxuri sunt aliniate temporal post-hoc prin corelație încrucișată (vezi 5.1), nefiind sincronizate la sursă."),
],

"Dataset complementar: date IMU în condiții reale de utilizare - Wassall NTNU (2025)": [
("p", "Pentru analiza comportamentului algoritmilor în scenarii apropiate de utilizarea cotidiană, se utilizează datasetul complementar Wassall NTNU (2025). În forma sa publică, acesta conține date de la 20 de utilizatori de proteză de membru inferior (11 transtibial, 8 transfemural, 1 bilateral); în analiza de față au fost procesați efectiv 16 participanți (atât transtibiali, cât și transfemurali), restul fiind excluși din cauza datelor incomplete. Datele au fost colectate exclusiv cu senzori inerțiali purtabili (Xsens), la 100 Hz, în condiții reale de teren, fără un sistem optic de referință."),
("p", "Fiecare probă conține patru senzori inerțiali — tibie protetică, coapsă protetică, trunchi (la nivel ~L4) și tibie contralaterală — iar activitățile acoperă mers pe teren plan, scări, pante, suprafețe instabile (iarbă, teren denivelat), cu și fără dispozitive de sprijin (baston). Deoarece datasetul Wassall este eșantionat la 100 Hz, asemănător ca natură cu cel principal, aceiași algoritmi de preprocesare și detecție pot fi reutilizați, viteza unghiulară fiind preluată direct din giroscop (Gyr_Y, convertită din rad/s în °/s). Etichetele de teren disponibile în dataset (plan, iarbă, scări — urcare/coborâre, pantă — urcare/coborâre, pietriș, denivelat) permit stratificarea analizei pe condiții."),
],

"GaitRec": [
("p", "Datasetul GaitRec (peste 75.000 de probe bilaterale bazate pe forțele de reacție la sol, GRF, achiziționate cu platforme de forță la ~1000 Hz, incluzând tipare de mers patologice) a fost identificat ca potențial set complementar pentru validări statistice la scară largă, comparații ale parametrilor temporali și studii de simetrie. În implementarea curentă, GaitRec NU este însă procesat: rezultatele lucrării se bazează exclusiv pe seturile Samala 2024 și Wassall 2025, integrarea GaitRec rămânând o direcție de dezvoltare ulterioară. Referința este menționată pentru completitudinea contextului, nu ca sursă a rezultatelor raportate."),
],

# ─────────────────────────── 4.5 PREPROCESARE ───────────────────────────────
"4.5.1. Filtrul low-pass Butterworth": [
("p", "Toate semnalele inerțiale utilizate în detecția evenimentelor și în calculul cinematicii sunt filtrate cu un filtru Butterworth low-pass de ordinul 4, aplicat în regim zero-phase prin funcția filtfilt din biblioteca scipy.signal. Filtrarea bidirecțională (forward–backward) anulează complet defazajul introdus de filtru — proprietate esențială, deoarece un filtru cauzal clasic ar deplasa în timp momentele evenimentelor detectate, introducând o eroare sistematică în estimarea contactului inițial și a desprinderii."),
("p", "Frecvența de tăiere este parametrizabilă, cu două valori implicite calibrate pe literatura de specialitate: 15 Hz pentru semnalele folosite la detecția evenimentelor de mers (viteza unghiulară a tibiei) și 6 Hz pentru calculul cinematicii articulare (unghiul gleznei), conform recomandărilor Winter (1991) și Catalfamo et al. (2010). Frecvența de tăiere este normalizată la frecvența Nyquist (Wn = fc / (fs/2)), iar implementarea validează explicit condiția 0 < Wn < 1. Lungimea de padding (padlen) este ajustată automat în funcție de lungimea semnalului, pentru a evita artefactele de margine pe înregistrările scurte."),
("p", "Decizie de implementare: ordinul 4 cu aplicare zero-phase produce un ordin efectiv de 8 (filtfilt aplică filtrul de două ori), ceea ce oferă o pantă de atenuare suficient de abruptă pentru a elimina zgomotul de înaltă frecvență fără a deforma componentele de frecvență joasă relevante pentru mers (sub 6–8 Hz). Alegerea regimului zero-phase, în detrimentul unui filtru cauzal mai simplu, este justificată de cerința de precizie temporală: o întârziere de fază necompensată ar muta momentul detectat al contactului inițial cu câteva zeci de milisecunde."),
],

"4.5.2. Magnitudinea accelerației": [
("p", "Pentru algoritmul de detecție în timp real (Maqbool R-GEDS), se calculează magnitudinea vectorială a accelerației tibiei ca normă euclidiană a celor trei componente măsurate de senzorul inerțial: |a| = √(ax² + ay² + az²). Spre deosebire de semnalul vitezei unghiulare, magnitudinea accelerației NU este filtrată — acest lucru este intenționat: vârfurile mecanice de impact de la momentul contactului călcâiului cu solul (de ordinul a ~1,5 g) sunt componente tranzitorii de înaltă frecvență care ar fi atenuate de o filtrare prealabilă, deci se păstrează semnalul brut pentru a conserva aceste spike-uri. Magnitudinea este apoi convertită în unități de g prin împărțire la 9,80665 m/s²."),
],

# ─────────────────────────── 4.6 TROJANIELLO ────────────────────────────────
"4.6. DETECȚIA EVENIMENTELOR DE MERS — ALGORITMUL TROJANIELLO": [
("p", "Primul algoritm de detecție a evenimentelor de mers implementat este o variantă offline bazată pe metodele Aminian (2002), Salarian (2004) și Trojaniello (2014), considerate referință în literatura de analiză a mersului din semnale inerțiale. Algoritmul operează exclusiv pe viteza unghiulară a tibiei în plan sagital (shank pitch rate)."),
("p", "Principiul de funcționare exploatează tiparul caracteristic al vitezei unghiulare a gambei: în faza de balans median (mid-swing), tibia atinge un vârf pozitiv pronunțat de viteză unghiulară, care servește drept ancoră temporală. Algoritmul identifică mai întâi aceste vârfuri prin funcția find_peaks, cu un prag de înălțime adaptiv, calculat ca 0,6 din percentila 95 a semnalului (peak_height = 0,6 × P95) și cu o distanță minimă între vârfuri corespunzătoare unei durate de minim 0,5 s, pentru a evita detecția dublă. Dacă percentila 95 este nepozitivă (semnal degenerat), algoritmul returnează un set gol de evenimente."),
("p", "Pornind de la fiecare vârf de mid-swing, contactul inițial (heel strike, HS) este localizat ca minimul local al vitezei unghiulare în fereastra [t_vârf, t_vârf + 350 ms], iar desprinderea degetelor (toe off, TO) ca minimul local în fereastra [t_vârf − 450 ms, t_vârf − 100 ms]. Un eveniment este acceptat numai dacă valoarea sa coboară sub pragul corespunzător: −20 °/s pentru HS și −10 °/s pentru TO la subiecții sănătoși."),
("h4", "4.6.1. Adaptarea pentru piciorul protetic"),
("p", "Subiecții purtători de proteză transtibială prezintă o dinamică redusă a tibiei pe partea protetică (amplitudini mai mici ale vitezei unghiulare, ca urmare a pierderii de propriocepție și a rigidității protezei pasive). Din acest motiv, atunci când algoritmul este aplicat în regim protetic, pragurile de detecție sunt relaxate la 60% din valorile pentru mersul sănătos, devenind −12 °/s pentru HS și −6 °/s pentru TO, conform recomandării Maqbool (2017). În studiul de validare, ambii algoritmi au fost rulați în regim protetic (prosthetic=True) pe întregul lot Samala, ca alegere conservatoare pentru un set eterogen de proteze."),
],

# ─────────────────────────── 4.7 MAQBOOL ────────────────────────────────────
"4.7. DETECȚIA EVENIMENTELOR DE MERS — ALGORITMUL MAQBOOL R-GEDS": [
("p", "Al doilea algoritm implementat este o variantă de tip R-GEDS (Real-time Gait Event Detection System), bazată pe Maqbool et al. (2017), proiectată pentru detecția cauzală, eșantion cu eșantion, potrivită controlului în timp real al unei proteze active. Spre deosebire de algoritmul Trojaniello, care necesită vizualizarea globală a semnalului (vârful de mid-swing este definit doar după ce a trecut), Maqbool poate fi rulat incremental și, în principiu, implementat pe un microcontroller."),
("p", "Algoritmul este structurat ca o mașină de stări cu trei stări nominale — STANCE, SWING și HS_PENDING — parcurse ciclic. Tranziția STANCE → SWING are loc atunci când viteza unghiulară depășește pragul ω_swing = 50 °/s, moment în care se emite evenimentul TO. După un timp minim petrecut în swing (t_min_swing = 0,2 s, anti-bouncing), dacă viteza unghiulară coboară sub ω_HS = −100 °/s, starea trece în HS_PENDING. Evenimentul HS este confirmat când magnitudinea accelerației depășește pragul de impact a_HS = 1,5 g. O perioadă refractară de 0,25 s după fiecare HS împiedică detecția prematură a următorului TO."),
("p", "Precizare importantă (de structură): perioada refractară NU este o stare separată a mașinii, ci o condiție temporală aplicată tranzițiilor. Pentru regimul protetic, pragurile sunt relaxate la ω_HS = −60 °/s și a_HS = 1,2 g, reflectând impactul atenuat al protezelor pasive (talpa SACH / lama de carbon absorb o parte din șocul de contact). Suplimentar, dacă confirmarea pe accelerație nu apare în ~600 ms de la TO, algoritmul acceptă HS pe baza criteriului de viteză unghiulară (mecanism de fallback, pentru a evita blocarea în HS_PENDING)."),
],

# ─────────────────────────── 4.8 UNGHI GLEZNĂ ───────────────────────────────
"4.8. CALCULUL UNGHIULUI GLEZNEI DIN IMU": [
("p", "Unghiul gleznei este reconstruit intern de platformă (funcția compute_ankle_angle), ca diferență a orientărilor de segment măsurate de sistemul inerțial: unghi_brut = −(shank_pitch − foot_pitch). Convenția adoptată este cea clinică standard (Perry & Burnfield, 2010): dorsiflexie pozitivă (+), plantarflexie negativă (−). Semnalul rezultat este calibrat la 0° într-un punct de referință (implicit la 0,5 s de la începutul înregistrării, sau la primul HS detectat în pipeline-ul de validare FSM), filtrat low-pass la 6 Hz (Winter, 1991) și limitat (clipping) la ±35°."),
("p", "Decizie de implementare (de ce un calcul propriu): sistemul Noraxon furnizează nativ coloane de tip „Ankle Dorsiflexion LT/RT”, însă acestea s-au dovedit, pe datasetul Samala 2024, inconsistente cu convenția clinică — prezintă semn opus și valori non-fiziologice în faza de balans. Din acest motiv, unghiul a fost recalculat din orientările de segment (shank pitch și foot pitch), care sunt mărimi măsurate direct de senzori. Rezultatul a fost validat cantitativ contra sistemului optic de referință (vezi Capitolul V): corelația medie Pearson este +0,65 și eroarea pătratică medie 8,75°, ceea ce confirmă fidelitatea reconstrucției."),
("p", "Limitarea (clipping) la ±35° este o decizie de respingere a artefactelor: ROM-ul fiziologic al gleznei la mers este de ~25–30° (până la ~40° în condiții extreme), astfel încât valorile care depășesc ±35° sunt cel mai probabil artefacte de orientare a senzorului. Se notează însă, ca limitare onestă, că pe câteva probe individuale clipping-ul taie și valori reale extreme, contribuind la o parte din eroarea reziduală observată în validare."),
],

# ─────────────────────────── 4.9 SEGMENTARE ─────────────────────────────────
"4.9. SEGMENTAREA CICLULUI DE MERS": [
("p", "Un ciclu complet de mers (stride) este definit ca intervalul delimitat de două evenimente HS consecutive ale aceluiași picior, [HS_i, HS_{i+1}]. În interiorul ciclului, faza de sprijin (stance) corespunde intervalului [HS_i, TO_i], iar faza de balans (swing) intervalului [TO_i, HS_{i+1}]. Ciclurile valide se formează doar atunci când un eveniment TO se găsește strict între cele două evenimente HS."),
("p", "Sistemul implementează o etapă de rejecție a outlierilor: se calculează mediana duratelor de stride, iar ciclurile a căror durată cade în afara intervalului [0,5 × mediană, 1,5 × mediană] sunt eliminate, conform practicii din Trojaniello (2014) și Pacini Panebianco (2018). Această filtrare elimină ciclurile aberante rezultate din detecții eronate (pași opriți, întoarceri, artefacte) fără a presupune o durată fixă a pasului, adaptându-se astfel la ritmul individual al fiecărui subiect."),
],

# ─────────────────────────── 4.10 PARAMETRI ─────────────────────────────────
"4.10. PARAMETRII TEMPORALI CALCULAȚI": [
("p", "Pe baza ciclurilor validate, funcția compute_gait_params agregă parametrii temporali clinici standard. Cadența totală se calculează ca dublul cadenței per picior: cadență = 2 × (60 × n_cicluri / durată_totală) [pași/min], deoarece numărarea HS-urilor unui singur picior corespunde unui pas pe acea parte, iar cadența clinică totală include și pasul contralateral."),
("p", "Durata stride-ului se raportează ca medie și abatere standard de eșantion (ddof = 1), iar variabilitatea pasului prin coeficientul de variație CV = abatere_standard / medie. Procentul fazei de sprijin se calculează la nivel de ciclu: stance% = 100 × (t_TO − t_HS) / (t_HS_următor − t_HS), iar procentul de balans ca swing% = 100 − stance%. Asimetria dintre piciorul protetic și cel intact este cuantificată prin indicele de simetrie Robinson (1987): SI = 2 × (P − I) / (P + I) × 100, unde valoarea 0 indică simetrie perfectă, iar P și I sunt valorile parametrului pe partea protetică, respectiv intactă."),
],

# ─────────────────────────── 4.11 FSM ───────────────────────────────────────
"4.11. FSM — CONTROLUL ADAPTIV AL GLEZNEI PROTETICE": [
("p", "Protezele active de gleznă (BiOM/Empower, Vanderbilt powered ankle, SpringActive) utilizează o mașină de stări finite (Finite State Machine — FSM) alimentată de senzori inerțiali pentru a identifica faza curentă a ciclului de mers și a comanda poziția/torque-ul corespunzător al gleznei. Platforma dezvoltată reproduce algoritmic această arhitectură: pentru fiecare eșantion al semnalului inerțial, FSM-ul determină starea curentă și emite un unghi de referință care, pe o proteză reală, ar reprezenta comanda transmisă motorului. Trebuie subliniat încă de la început că lotul Samala conține exclusiv proteze PASIVE (24 din 30 de tip SACH), astfel încât FSM-ul este aici o simulare offline a logicii de comutare a fazelor, nu un controller rulat pe hardware activ."),
("h4", "4.11.1. Cele 5 stări FSM"),
("p", "Mașina de stări implementată are cinci stări, parcurse în ordinea ciclului de mers. S1 — Loading Response: declanșată de evenimentul HS; funcția fiziologică este absorbția impactului. S2 — Mid-Stance: declanșată de detecția de foot-flat, definită ca |ω_shank| < 30 °/s menținut timp de 10 eșantioane consecutive (50 ms la 200 Hz); reprezintă trecerea tibiei peste piciorul-pivot. S3 — Push-Off: declanșată când unghiul de dorsiflexie depășește 3° SAU când s-a depășit 45% din durata mediană a stride-ului (mecanism de timeout); reprezintă propulsia. S4 — Early Swing: declanșată de evenimentul TO; repoziționarea gleznei pentru evitarea contactului cu solul. S5 — Late Swing: declanșată de vârful vitezei unghiulare (mid-swing); pregătirea următorului contact."),
("p", "Decizie de implementare: pragul de declanșare a push-off-ului a fost relaxat de la valoarea de ~8° din literatura pe subiecți sănătoși la 3°, pentru a se putea declanșa și la purtătorii de proteză cu amplitudine de dorsiflexie redusă; dacă nici acest prag nu este atins, FSM-ul comută pe baza fracției de fază (45% din stride). Toleranța la erori este asigurată printr-un timeout absolut pe stare (max_dwell = 1,5 × durata mediană a stride-ului, dar cel puțin 0,3 s), conform recomandării Varol, Sup & Goldfarb (2010), care forțează tranziția atunci când evenimentul așteptat nu apare. Evenimentele HS și TO au prioritate asupra logicii de stare: detecția unui HS forțează S1, iar a unui TO forțează S4."),
("h4", "4.11.2. Setpoints per activitate"),
("p", "Pentru fiecare stare se definește un unghi de referință (setpoint). Este esențial de subliniat că aceste valori NU reprezintă unghiuri observate fiziologic, ci ECHILIBRE VIRTUALE DE IMPEDANȚĂ (θ_eq), în sensul controllerului de impedanță Sup, Bohara & Goldfarb (2008). Valorile pentru mersul pe plan (level) sunt: S1 = −8°, S2 = −15°, S3 = −25°, S4 = −5°, S5 = −3° — toate în plantarflexie, formând o curbă monoton descrescătoare în faza de sprijin, ancorată direct în Tabelul 5 din Sup (2008). Tabelul 4.1 prezintă seturile complete de setpoints pentru cele cinci regimuri de activitate (level, urcare/coborâre scări, urcare/coborâre pantă), scalate proporțional din Sup, Varol & Goldfarb (2012) și Bartlett et al. (2021)."),
("p", "Relația dintre echilibrul comandat și unghiul observat este θ_observat = θ_eq + M_ext / K, unde M_ext este momentul extern produs de forța de reacție a solului (GRF), iar K este rigiditatea impedanței gleznei. Această distincție este fundamentală pentru interpretarea corectă a rezultatelor de validare din Capitolul V: un controller de impedanță NU urmărește o traiectorie de poziție, ci comandă un echilibru în jurul căruia glezna se deformează elastic sub sarcină."),
("h4", "4.11.3. Generarea traiectoriei continue (PCHIP)"),
("p", "Setpoint-urile discrete (constante pe durata fiecărei stări) sunt transformate într-o traiectorie continuă, netedă, comandabilă unui motor real, prin interpolare PCHIP (Piecewise Cubic Hermite Interpolating Polynomial) din scipy.interpolate. Pentru fiecare segment de stare, se plasează un punct de control (waypoint) la 30% din durata stării, astfel încât traiectoria să atingă rapid setpoint-ul și să-l mențină. Traiectoria este apoi netezită cu o medie mobilă scurtă (fereastră de 40 ms)."),
("p", "Decizie de implementare: alegerea PCHIP în locul unei interpolări Hermite cubice clasice (CubicHermiteSpline) este justificată de proprietatea de monotonie între puncte de control — PCHIP garantează că traiectoria nu depășește (overshoot) valorile setpoint-urilor. Versiunea anterioară, bazată pe spline Hermite cu derivate centrate, producea overshoot vizibil (până la 22° peste setpoint), inacceptabil biomecanic, deoarece ar fi comandat dorsiflexie tocmai în faza de push-off (când se cere plantarflexie)."),
],

# ─────────────────────────── 4.12 DASHBOARD ─────────────────────────────────
"4.12. VIZUALIZARE ȘI DASHBOARD INTERACTIV": [
("p", "Platforma include un dashboard interactiv dezvoltat în Streamlit, organizat pe mai multe pagini accesibile dintr-un meniu lateral. Fișierul app.py este pagina de start, iar fiecare modul din directorul pages/ devine o pagină separată; un modul partajat (_shared.py) definește funcții de încărcare a datelor decorate cu @st.cache_data, astfel încât fiecare fișier CSV să fie citit o singură dată pe sesiune. Graficele sunt interactive (Plotly, cu zoom și pan)."),
("p", "Pagina 1 (Explorare semnale) permite vizualizarea semnalelor inerțiale brute, cu selecția subiectului, probei, lateralității și a unei frecvențe de tăiere pentru filtru. Pagina 2 (Detecție evenimente) afișează evenimentele HS și TO detectate de cei doi algoritmi (Trojaniello și Maqbool) suprapuse peste viteza unghiulară a gambei. Pagina 3 (Parametri temporali) prezintă tabele cu cadența, durata pasului, procentul de sprijin și variabilitatea, separat pentru piciorul protetic și cel intact, plus un sumar comparativ pe rol. Pagina 4 (Simulator FSM) vizualizează stările FSM pe parcursul ciclului și suprapune unghiul comandat peste cel real. Pagina 5 (Comparație activități) agregă parametrii Wassall pe tip de teren. Pagina 6 (Simulator proteză) conține animația 2D a componentei protetice."),
("p", "Animația 2D reprezintă, în plan sagital, componenta protetică (pilon + gleznă + talpă). Tibia (pilonul) este un segment rigid de lungime fixă L_TIBIA = 0,40 m și înclinare oblică constantă de +7° (PYLON_TILT_DEG), care culisează rigid pe verticală; genunchiul urcă/coboară împreună cu glezna, păstrând constant vectorul tibial. Talpa pivotează în jurul gleznei după unghiul exact din date (FSM sau IMU), fără scalare. În faza de sprijin, cel mai jos punct al tălpii atinge solul, glezna culisând vertical conform geometriei; în balans, glezna se ridică cu 6 cm (SWING_LIFT) peste poziția neutră. Pentru a evita salturile vizuale la momentele TO și HS, poziția gleznei se interpolează lin pe o fereastră de tranziție de ~80 ms. Această reprezentare permite vizualizarea directă a deciziilor de control și, prin alegerea sursei de unghi, compararea vizuală între comanda FSM și unghiul real estimat din IMU."),
],

# ═══════════════════════════ CAPITOLUL V ════════════════════════════════════
"5.1. PIPELINE-UL DE VALIDARE": [
("p", "Algoritmii bazați pe semnale inerțiale trebuie validați contra unui sistem de referință independent. Standardul în biomecanică este captura optică a mișcării (Optical Motion Capture, OMC) — sisteme cu camere infraroșu și markeri reflectorizanți, de precizie milimetrică. Datasetul Samala 2024 furnizează, pentru fiecare probă, fișiere C3D cu pozițiile 3D ale markerilor, eșantionate la 200 Hz (identic cu IMU)."),
("p", "Evenimentele de referință HS și TO se extrag din datele OMC prin algoritmul Zeni et al. (2008), care folosește poziția pe axa de mers (X) a markerilor în raport cu centrul pelvisului: HS corespunde maximului local al coordonatei (călcâi − pelvis).x (călcâiul cel mai avansat față de corp), iar TO minimului local al coordonatei (vârf − pelvis).x. În implementare, markerul de călcâi (HEEL) și metatarsianul 3 (MTH3, ca proxy pentru vârf) sunt utilizați împreună cu centrul pelvic calculat ca medie a markerilor PELVIS stânga/dreapta; axa de mers este aleasă automat ca direcția cu amplitudinea maximă de deplasare. Pozițiile markerilor sunt filtrate low-pass la 6 Hz, iar evenimentele sunt separate de o distanță minimă de 0,4 s."),
("p", "O dificultate specifică datasetului Samala este că înregistrările inerțiale acoperă întreaga probă (~14 s), în timp ce fereastra de captură optică este semnificativ mai scurtă (mediană ~3,7 s, în jur de 4–4,5 s). Cele două fluxuri nu sunt sincronizate la sursă, astfel încât alinierea temporală se realizează algoritmic, prin corelație încrucișată normalizată (cross-correlation) pe semnalul unghiului gleznei — disponibil în ambele surse, cu aceeași convenție. Offset-ul optim astfel determinat este folosit pentru a suprapune evenimentele și traiectoriile pe aceeași axă temporală. Metricile de validare (MAE, RMSE, NRMSE, PCC) sunt calculate automat și exportate în fișiere CSV structurate."),
],

"5.2. VALIDAREA EVENIMENTELOR HS/TO": [
("p", "Validarea evenimentelor a vizat potențial 30 de subiecți × 5 probe × 2 laturi = 300 perechi probă-latură; în practică, subiectul S04 a fost exclus (aliniere OMC–IMU eșuată), rezultând 29 de subiecți și un total de 290 de perechi efectiv analizate per algoritm. Potrivirea dintre evenimentele detectate și cele de referință s-a făcut cu o toleranță de ±150 ms (prag raportat ca acceptabil de Pacini Panebianco, 2018), mai permisivă decât pragul strict de proiectare (25 ms pentru HS, 50 ms pentru TO)."),
("p", "Rezultatele agregate inițiale (Tabelul 5.1) arată erori de timing (MAE) de 60–80 ms și o sensibilitate de 0,58–0,65: algoritmul Maqbool depășește Trojaniello la detecția HS (MAE 60,2 ms vs. 79,8 ms; sensibilitate 0,633 vs. 0,584), în timp ce Trojaniello este mai bun la TO (MAE 60,7 ms vs. 76,9 ms). Precizia (PPV) brută este însă scăzută (~0,28–0,29), iar scorul F1 ~0,38."),
("p", "Analiza cauzelor a evidențiat că precizia scăzută este în mare parte un artefact de comparație, nu un defect al algoritmului: detectorul inerțial identifică evenimente pe întreaga probă de ~14 s, în timp ce referința OMC acoperă doar fereastra de ~3,7 s. Astfel, peste jumătate dintre detecțiile inerțiale cad în afara intervalului în care există ground-truth și sunt numărate ca false pozitive, deși cele mai multe sunt, foarte probabil, pași reali fără referință optică. Pentru o comparație echitabilă (măr-cu-măr), evaluarea a fost refăcută restrângând evenimentele inerțiale la fereastra acoperită de OMC. În acest regim, precizia crește semnificativ (PPV de la ~0,28 la 0,65–0,70; F1 la 0,61–0,67), în timp ce sensibilitatea rămâne neschimbată (0,58–0,65) — confirmând că restrângerea elimină doar falsele pozitive din afara ferestrei, fără a modifica artificial detecția în interiorul ei."),
("p", "Suplimentar, s-a observat un decalaj temporal sistematic între definiția inerțială a evenimentului și definiția Zeni-OMC. Prin scăderea acestui decalaj (corecție de offset), eroarea MAE coboară sub 30 ms, încadrându-se în pragul de proiectare. Trebuie precizat onest că această corecție este estimată per probă din chiar datele evaluate, deci valoarea de ~26–30 ms reprezintă eroarea reziduală după eliminarea offset-ului, nu o acuratețe direct deployabilă în câmp; metrica de raportare principală rămâne MAE-ul brut de 60–80 ms, care se încadrează deja în intervalul publicat pe pacienți amputați (Maqbool, 2017). Sensibilitatea modestă rămâne o limitare reală a metodei pe proteze pasive, prezentată ca atare."),
],

"5.3. VALIDAREA TRAIECTORIEI UNGHIULUI GLEZNEI": [
("p", "Validarea traiectoriei unghiului gleznei a fost realizată pe perechile probă-latură cu o suprapunere temporală de cel puțin 1 s între semnalul predicționat și cel de referință. Tabelul 5.2 prezintă trei comparații față de OMC: (i) unghiul real estimat direct din IMU (compute_ankle_angle); (ii) echilibrul de impedanță comandat de FSM (θ_eq, traiectoria brută); (iii) unghiul observat reconstruit din bucla de impedanță (θ_observat = θ_eq + M_GRF/K)."),
("p", "Unghiul estimat din IMU se validează foarte bine: RMSE 8,75°, NRMSE 0,53 și corelație Pearson +0,65 (toate cele 29 de subiecți având PCC pozitiv, între 0,27 și 0,95). Această valoare se încadrează în intervalul raportat pentru sisteme inerțiale și confirmă fidelitatea reconstrucției unghiului din orientările de segment măsurate. Diferența față de intervalul optim publicat (~5°) se explică parțial prin amestecul de cinematică intactă și protetică din lot, prin variabilitatea inter-subiect și prin limitarea (clipping) la ±35° care taie câteva valori extreme reale."),
("p", "Comparația directă a echilibrului de impedanță comandat (θ_eq) cu unghiul OMC produce o corelație negativă (PCC mediu −0,24) și un RMSE de 13,72°. Acest rezultat NU reprezintă o eroare de implementare, ci o consecință conceptuală fundamentală: setpoint-urile FSM sunt echilibre de impedanță monoton descrescătoare în plantarflexie (de la −8° la −25° în stance), în timp ce unghiul cinematic real observat crește în dorsiflexie în stance (rocker fiziologic, de la ~+5° la ~+15° pe partea intactă). Tendințele fiind opuse, corelația cu echilibrul brut este, prin construcție, negativă — fapt confirmat de literatura de control de impedanță (Sup & Goldfarb), unde controllerele de acest tip NU se validează prin urmărirea unei traiectorii, ci prin reproducerea formei profilului biomecanic."),
("p", "Pentru a apropia comparația de fizica reală, s-a reconstruit unghiul observat prin bucla de impedanță, adăugând la echilibrul comandat deflexia produsă de momentul GRF (M_GRF/K, cu un profil GRF normativ scalat la greutatea reală a subiectului și o rigiditate K = 3,0 N·m/° în plaja fiziologică). În acest regim, corelația devine pozitivă (PCC +0,11) și RMSE scade la 8,28°. Acest rezultat trebuie interpretat cu prudență și onestitate: deplasarea semnului corelației este produsă în mare parte de profilul GRF normativ — un șablon dependent de fază, nu de cinematica reală a subiectului — astfel încât bucla de impedanță demonstrează corect DIRECȚIA fizică a relației (de ce unghiul observat se decuplează de echilibrul comandat), dar nu reconstruiește unghiul individual al subiectului. Concluzia metodologic corectă este că PCC negativ inițial era un artefact al metricii alese, iar evaluarea adecvată a unui controller de impedanță se face prin suprapunere de profil, nu prin corelație punct-cu-punct."),
],

"5.4. REZULTATE BIOMECANICE — COMPARAȚIE PROTETIC VS. INTACT": [
("p", "Analiza parametrilor temporali pe cohorta Samala (probele Walking1) a comparat piciorul protetic cu cel intact (Tabelul 5.3). Rezultatele confirmă patru constatări biomecanice consistente cu literatura. (1) Compensare temporală absentă: cadența (100,1 vs. 100,3 pași/min) și durata stride-ului (1,215 vs. 1,212 s) sunt practic identice între părți (diferență sub 0,3%), indicând că pacienții nu își ajustează ritmul, ci adoptă o strategie compensatorie spațială. (2) Redistribuirea sprijinului: procentul de sprijin pe partea protetică este cu 3,8 puncte procentuale mai mic (51,7% vs. 55,5%), pacientul transferând greutatea prematur pe partea sănătoasă — consistent cu Sanderson & Martin (1997)."),
("p", "(3) Pierderea amplitudinii de mișcare a gleznei: ROM-ul protetic este de 17,0° față de 38,6° pe partea intactă (reducere de ~56%), în acord cu Hsu et al. (2006), care raportează o reducere de ~60% pentru protezele pasive. (4) Variabilitate crescută: abaterea standard a procentului de sprijin este de ~2,4 ori mai mare pe partea protetică (9,8 vs. 4,1), indicând un control motor mai puțin stabil — factor de risc documentat pentru căderi. Aceste constatări sunt agregate pe 30 de laturi protetice și 29 intacte (S04 exclus)."),
],

"5.5. REZULTATE — MERS PE TEREN (ANALIZA WASSALL)": [
("p", "Datasetul complementar Wassall NTNU (2025) permite analiza comportamentului în condiții reale de teren, în absența unui sistem optic. Trebuie precizat că, deși datasetul public conține 20 de utilizatori (11 transtibial, 8 transfemural, 1 bilateral), analiza de față a procesat efectiv 16 participanți (atât transtibiali cât și transfemurali), restul fiind excluși din cauza datelor incomplete. Fiecare probă conține patru senzori inerțiali (tibie protetică, coapsă protetică, trunchi și tibie contralaterală), fără markeri optici de referință; analiza utilizează cu precădere semnalul tibiei protetice."),
("p", "Tabelul 5.4 prezintă parametrii medii pe tip de teren. Scările (stair) reprezintă condiția cea mai solicitantă: variabilitatea pasului (CV) atinge valoarea maximă de 0,145 (de ~2,8 ori mai mare decât pe teren plan, 0,051), cadența scade la minimul de 82,8 pași/min, durata stride-ului crește la 1,51 s, iar procentul de sprijin urcă la 59,5%. Un CV peste 0,13 este un factor de risc de cădere bine documentat (Hausdorff, 2007). Pietrișul (gravel) este al doilea cel mai dificil teren (cadență 87,5, CV 0,088), în timp ce panta (slope, CV 0,061) rămâne apropiată de terenul plan, pacienții adaptându-se bine la o înclinare structural constantă. Iarba (grass) prezintă cea mai mare cadență medie (105,3), însă cu o variabilitate ridicată (CV 0,083)."),
("p", "Comparând curba comandată de FSM cu unghiul observat pe proteza pasivă (SACH), se evidențiază argumentul empiric pentru necesitatea protezelor active: FSM comandă în push-off o plantarflexie de −25°, în timp ce unghiul real observat pe SACH atinge o plantarflexie redusă, rezultând un deficit de propulsie neexploatat. Energia de push-off a unei proteze pasive este de doar 15–20% din cea a mersului sănătos, cu un cost energetic crescut cu 20–30% (Waters, 1976; Hsu, 2006). Arhitectura FSM implementată este pregătită algoritmic pentru execuția pe o proteză activă — lipsește doar hardware-ul de acționare."),
],

"5.6.1. Limitări ale dataseturilor": [
("p", "Datasetul Samala 2024: (a) fereastra de captură optică este scurtă (~3,7 s mediană, față de ~14 s pentru IMU), limitând numărul de evenimente disponibile pentru potrivire (3–4 stride-uri per probă) și făcând precizia reală pe întreaga probă nemăsurabilă în absența unui ground-truth continuu; (b) toate protezele sunt pasive (predominant SACH), ceea ce nu permite testarea controllerului FSM pe o gleznă activă reală; (c) achiziția este doar pe teren plan, astfel încât setpoint-urile pentru scări și pantă rămân netestate empiric; (d) subiectul S04 a fost exclus din validare; (e) numărul de subiecți (30) limitează analizele stratificate pe tip de proteză."),
("p", "Datasetul Wassall 2025: (a) doar patru senzori inerțiali, fără markeri la nivelul piciorului sau al gleznei; (b) absența unui sistem optic înseamnă lipsa unui ground-truth pentru validarea evenimentelor; (c) condițiile de scări combină urcarea și coborârea, fără posibilitatea de separare; (d) datasetul conține și utilizatori transfemurali, ceea ce introduce eterogenitate în lotul analizat."),
("h4", "5.6.2. Limitări algoritmice"),
("p", "Sensibilitatea detecției HS rămâne modestă (0,58 pentru Trojaniello), sub ținta de proiectare, ca urmare a decalajului sistematic dintre definiția inerțială și cea optică a evenimentului și a ferestrei OMC scurte care reduce statistica disponibilă. Eroarea MAE brută (60–80 ms) ar putea fi redusă printr-o corecție de bias calibrată pe un set independent. Limitarea (clipping) la ±35° a unghiului gleznei ascunde câteva valori reale extreme. Setpoint-urile FSM sunt fixe per activitate și nu se adaptează automat la viteza de mers."),
("p", "În ansamblu, performanța obținută se încadrează în reperele realiste din literatura aplicată pe pacienți amputați (Maqbool, 2017; Pacini Panebianco, 2018): erori MAE de 50–80 ms și sensibilități de 60–75% sunt considerate acceptabile pentru această clasă de aplicații. Corelația negativă FSM–OMC este un rezultat diagnostic, nu un defect: ea confirmă că FSM-ul implementat respectă modelul de impedanță Sup (2008), iar evaluarea sa corectă necesită metode de suprapunere de profil, nu metrici de urmărire de traiectorie. Reconstrucția unghiului din IMU (PCC +0,65, RMSE 8,75°) rămâne rezultatul de validare cel mai solid al lucrării."),
],

}
